root: ./src
build_name: stargate
build_log: /tmp/runner_build.log
log_color: true
app_name: main
executable_path: ./bin/stargate
build_script: go build -o ./bin/stargate/src main.go
run_script: ./bin/stargate